version: "2"
services:
  hw-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - "mongodb"
    environment:
      - MONGODBURL=mongodb://hw-db/mongoDBDatabase
  hw-db:
    build: ./db
    ports:
      - "27017:27017"